[package]
name = "draft-helper"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
publish = false

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "vitaliytv:draft-helper"

[package.metadata.component.target]
path = "wit"
world = "draft-helper-plugin"

[package.metadata.component.target.dependencies]
"vitaliytv:gmail" = { path = "wit/deps/gmail" }

[dependencies]
wit-bindgen = { version = "=0.60.0", features = ["async-spawn"] }
